create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null default 'TAWY',
  slug text not null unique,
  collection text not null,
  category text not null,
  price numeric(10, 2) not null default 0,
  image_url text not null,
  sizes text[] not null default '{}',
  colors text[] not null default '{}',
  color_images jsonb not null default '{}',
  color_media jsonb not null default '{}',
  in_stock boolean not null default true,
  description text not null default '',
  size_fit text not null default '',
  shipping text not null default 'Free shipping on all orders. Returns accepted within 14 days.',
  best_seller boolean not null default false,
  status text not null default 'active' check (status in ('draft', 'active', 'archived')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Migration for existing databases: add the per-color media gallery column.
alter table public.products add column if not exists color_media jsonb not null default '{}';

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_reference text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  delivery_city text not null,
  delivery_address text not null,
  delivery_notes text,
  payment_method text not null default 'cod' check (payment_method in ('cod', 'online')),
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid', 'failed', 'refunded')),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled')),
  total_amount numeric(10, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  product_slug text,
  product_name text not null,
  brand text not null default 'TAWY',
  selected_size text not null,
  selected_color text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null default 0,
  line_total numeric(10, 2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products
for select
to anon, authenticated
using (status = 'active');

drop policy if exists "Anyone can create COD orders" on public.orders;
create policy "Anyone can create COD orders"
on public.orders
for insert
to anon, authenticated
with check (payment_method = 'cod');

drop policy if exists "Anyone can create COD order items" on public.order_items;
create policy "Anyone can create COD order items"
on public.order_items
for insert
to anon, authenticated
with check (true);

insert into public.products (
  id, name, brand, slug, collection, category, price, image_url, sizes, colors,
  color_images, color_media, in_stock, description, size_fit, shipping, best_seller, status, sort_order
) values
(
  1,
  'Classic Denim Jacket',
  'TAWY',
  'classic-denim-jacket',
  'denim',
  'jackets',
  89.99,
  'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
  array['S', 'M', 'L', 'XL'],
  array['Blue', 'Black'],
  '{"Blue":"https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80","Black":"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80"}',
  '{"Blue":{"images":["https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?auto=format&fit=crop&w=800&q=80"],"video":"https://www.w3schools.com/html/mov_bbb.mp4"},"Black":{"images":["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=800&q=80"]}}',
  true,
  'A structured TAWY layer cut for cool desert evenings.',
  'Fits true to size. Take your normal size.',
  'Free shipping on all orders. Returns accepted within 14 days.',
  false,
  'active',
  10
),
(
  2,
  'Vintage T-Shirt',
  'TAWY',
  'vintage-t-shirt',
  'summer25',
  't-shirts',
  29.99,
  'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=800&q=80',
  array['S', 'M', 'L'],
  array['White', 'Black', 'Gray'],
  '{"White":"https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=800&q=80","Black":"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80","Gray":"https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=800&q=80"}',
  '{"White":{"images":["https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=800&q=80"]}}',
  true,
  'A soft cotton piece shaped for Red Sea light and everyday ease.',
  'Fits true to size. Take your normal size.',
  'Free shipping on all orders. Returns accepted within 14 days.',
  true,
  'active',
  20
),
(
  3,
  'Cargo Jorts',
  'TAWY',
  'cargo-jorts',
  'denim',
  'shorts',
  59.99,
  'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80',
  array['30', '32', '34', '36'],
  array['Blue', 'Black'],
  '{"Blue":"https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80","Black":"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80"}',
  '{}',
  true,
  'Utility-inspired cotton with a clean TAWY silhouette.',
  'Fits true to size. Take your normal size.',
  'Free shipping on all orders. Returns accepted within 14 days.',
  false,
  'active',
  30
),
(
  4,
  'Oversized Hoodie',
  'TAWY',
  'oversized-hoodie',
  'summer25',
  'hoodies',
  79.99,
  'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=800&q=80',
  array['S', 'M', 'L', 'XL'],
  array['Gray', 'Black', 'Navy'],
  '{"Gray":"https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=800&q=80","Black":"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80","Navy":"https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?auto=format&fit=crop&w=800&q=80"}',
  '{}',
  true,
  'An easy oversized layer for coastal nights and slow mornings.',
  'Fits true to size. Take your normal size.',
  'Free shipping on all orders. Returns accepted within 14 days.',
  true,
  'active',
  40
),
(
  5,
  'Graphic Tee',
  'TAWY',
  'graphic-tee',
  'ss25',
  't-shirts',
  34.99,
  'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80',
  array['S', 'M', 'L', 'XL'],
  array['White', 'Black'],
  '{"White":"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80","Black":"https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=800&q=80"}',
  '{}',
  false,
  'A TAWY cotton tee with a clean graphic presence.',
  'Fits true to size. Take your normal size.',
  'Free shipping on all orders. Returns accepted within 14 days.',
  true,
  'active',
  50
),
(
  6,
  'Denim Shirt',
  'TAWY',
  'denim-shirt',
  'denim',
  'shirts',
  69.99,
  'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?auto=format&fit=crop&w=800&q=80',
  array['S', 'M', 'L'],
  array['Blue', 'Light Blue'],
  '{"Blue":"https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?auto=format&fit=crop&w=800&q=80","Light Blue":"https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80"}',
  '{}',
  true,
  'A crisp denim shirt balanced between heritage texture and modern wear.',
  'Fits true to size. Take your normal size.',
  'Free shipping on all orders. Returns accepted within 14 days.',
  false,
  'active',
  60
),
(
  7,
  'Bag',
  'TAWY',
  'bag',
  'accessories',
  'accessories',
  0,
  'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80',
  array['One Size'],
  array['Black', 'Blue', 'Green', 'Gold'],
  '{"Black":"https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80","Blue":"https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80","Green":"https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80","Gold":"https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80"}',
  '{}',
  true,
  'A complimentary TAWY bag prepared with your order.',
  'One size.',
  'Included with eligible orders. Returns accepted within 14 days.',
  false,
  'active',
  70
)
on conflict (id) do update set
  name = excluded.name,
  brand = excluded.brand,
  slug = excluded.slug,
  collection = excluded.collection,
  category = excluded.category,
  price = excluded.price,
  image_url = excluded.image_url,
  sizes = excluded.sizes,
  colors = excluded.colors,
  color_images = excluded.color_images,
  color_media = excluded.color_media,
  in_stock = excluded.in_stock,
  description = excluded.description,
  size_fit = excluded.size_fit,
  shipping = excluded.shipping,
  best_seller = excluded.best_seller,
  status = excluded.status,
  sort_order = excluded.sort_order,
  updated_at = now();

select setval(pg_get_serial_sequence('public.products', 'id'), (select max(id) from public.products));
